import type { Metadata } from "next";
import { Cormorant_Garamond } from "next/font/google";
import Header from "./components/header";
import BackgroundImage from "./components/backgroundImage";
import styles from "./page.module.css";

import "./globals.css";
import SideName from "./components/sidename";

const inter = Cormorant_Garamond({ subsets: ["latin"], weight: ['300'], });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <SideName />

        <main className={styles.main}>
          {children}
        </main>

      </body>
    </html>
  );
}
